import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Navbar from './components/Navbar'
import Foobar from './components/Foobar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Phanox Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Phanoax Ecommerce</title>
      </head>
      <body>
        <Navbar />
        {children}
        <Foobar />
      </body>
    </html>
  )
}
